In [8]:
import pandas as pd

In [53]:
df = pd.read_json("books/dsm-tree/dsm5_selected_chapters_tree.jsonl", lines=True)

df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
0,e5cf362b-2ff0-4c7e-be69-05bd426e1938,NaN,root,Chapter 1,,34,parent,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
1,30b04a24-ef1e-4a70-b522-9f144b51c721,e5cf362b-2ff0-4c7e-be69-05bd426e1938,heading,Neurodevelopmental Disorders,Neurodevelopmental Disorders,34,parent,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
2,88eb8056-30b0-4204-9ec4-75b0bd74e170,30b04a24-ef1e-4a70-b522-9f144b51c721,paragraph,NaN,"Prior to DSM-5, the name of this chapter was e...",34,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...
3,144dd110-20d1-49e5-b628-1d223e049be7,30b04a24-ef1e-4a70-b522-9f144b51c721,heading,Quick Guide to the Neurodevelopmental Disorders,Quick Guide to the Neurodevelopmental Disorders,34,parent,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...
4,31e10ee3-d2a9-4ab1-ae80-9589f1e33b7c,144dd110-20d1-49e5-b628-1d223e049be7,paragraph,NaN,"In every Quick Guide, the page number followin...",34,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...
...,...,...,...,...,...,...,...,...,...,...
17667,466f6751-7074-4917-bcbd-383be49e4dc8,ca0549e3-b27f-4157-b22b-481b60a734c4,heading,F17.209 Unspecified Tobacco-Related Disorder,F17.209 Unspecified Tobacco-Related Disorder,427,leaf,DSM5_ME,Chapter 15: Substance-Related and Addictive Di...,Chapter 15: Substance-Related and Addictive Di...
17668,42bc762f-1783-4c53-87af-15aedd0ef140,ca0549e3-b27f-4157-b22b-481b60a734c4,heading,Other (or Unknown) Substance-Related Disorders,Other (or Unknown) Substance-Related Disorders,427,parent,DSM5_ME,Chapter 15: Substance-Related and Addictive Di...,Chapter 15: Substance-Related and Addictive Di...
17669,45e6309f-9736-46f4-9a2e-79c21eac319b,42bc762f-1783-4c53-87af-15aedd0ef140,paragraph,NaN,The category of other (or unknown) substance-r...,427,leaf,DSM5_ME,Chapter 15: Substance-Related and Addictive Di...,Chapter 15: Substance-Related and Addictive Di...
17670,24f93c36-3649-416a-adae-6681d3d3347c,42bc762f-1783-4c53-87af-15aedd0ef140,paragraph,NaN,Here are some examples of the substances that ...,427,parent,DSM5_ME,Chapter 15: Substance-Related and Addictive Di...,Chapter 15: Substance-Related and Addictive Di...
17671,befd358f-517a-4437-a0dd-0310bf711744,24f93c36-3649-416a-adae-6681d3d3347c,paragraph,Anabolic steroids.,Anabolic steroids. The value to users of the a...,427,leaf,DSM5_ME,Chapter 15: Substance-Related and Addictive Di...,Chapter 15: Substance-Related and Addictive Di...

In [54]:
first_paragraphs_df = df.groupby(['book_name','page']).nth(1).sort_values("page")
first_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
1,30b04a24-ef1e-4a70-b522-9f144b51c721,e5cf362b-2ff0-4c7e-be69-05bd426e1938,heading,Neurodevelopmental Disorders,Neurodevelopmental Disorders,34,parent,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
17619,2b4cb0db-5d23-40d4-aed4-96cbe6ee2184,8ad957e1-69e6-4dd6-a465-b7c865cb0f5a,heading,Communication and Learning Disorders,Communication and Learning Disorders,35,parent,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
153,3fe189bb-a4a6-4667-9a06-58b65b8ca518,bfa66cb7-dd66-43cd-bb6e-28c84796f258,paragraph,NaN,**Pica.** The patient eats material that is no...,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
12,964440e8-d98c-4b69-8fd5-4beafab99d96,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,Individuals with intellectual developmental di...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
19,15fa21e9-f554-46ac-abce-d1e4bbe889f2,9bc86a08-a9b4-4441-910a-a6a945c5f134,paragraph,NaN,"IDD may have biological or social causes, or b...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
...,...,...,...,...,...,...,...,...,...,...
17364,2c26e2b3-3e06-4f8e-83f8-d987827624fe,1a27752c-1037-4209-a430-8be9706c90d4,paragraph,NaN,not form part of the trait definition. Importa...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders
17450,292b43b1-6671-4ba4-a9b4-18a162a6376b,8e218f22-4a5d-4442-9a0b-0504cd5a3eaa,paragraph,NaN,"psychiatric diagnoses. Notably, knowing the le...",1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders
17468,c631e5b6-47b3-4b0a-864b-d40d1574343f,219d848f-24e5-45c1-a786-584f6849927c,paragraph,NaN,esteem controlled by exaggerated concern about...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders
17485,ca098fe9-5f00-4f48-8690-983e90c4b654,cbed2c31-6e2f-4075-acc4-eb71f5d03451,paragraph,NaN,distortions and confusion around self-appraisa...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders
17509,e682fae7-2a4e-4011-894d-077ca1efa6c9,d8586892-81d2-41de-a3b8-8ebc277b60f3,paragraph,Suspiciousness,Suspiciousness Expectations of—and sensitivity...,1166,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders

In [71]:
last_paragraphs_df = df.groupby(['book_name','page']).nth(-1).sort_values("page")
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
10,435d3fa2-44dc-4ae4-a8a8-7abd27aae0f7,0d5aa42c-32b4-4885-9f1d-44c3e6b6c7ac,list_item,NaN,Unspecified intellectual developmental disorde...,34,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...
17638,d56d3510-19b9-4129-b12d-63916321797c,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...
170,cfaeae33-1a2a-4349-91a2-67a6d0b4cb19,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder**,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...
17,33d3dfc4-de21-4972-b808-41080469ec6a,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
29,5fec48f5-225f-4a20-a03a-333322a97619,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...
...,...,...,...,...,...,...,...,...,...,...
17370,edeaffcd-75b0-4140-9a85-5b5a59656504,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17466,eb863a41-5037-460c-ae2a-57410f977a2b,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17483,28e88104-952a-4b24-a049-052767b87e83,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17507,e9299962-4d2a-4085-8c5f-454fe593d446,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17529,3d230958-81d5-45e6-844e-b50baafa801f,d8586892-81d2-41de-a3b8-8ebc277b60f3,paragraph,NaN,902,1166,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders

In [72]:
last_paragraphs_df = last_paragraphs_df[last_paragraphs_df['node_type_in_tree']=='leaf']
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
10,435d3fa2-44dc-4ae4-a8a8-7abd27aae0f7,0d5aa42c-32b4-4885-9f1d-44c3e6b6c7ac,list_item,NaN,Unspecified intellectual developmental disorde...,34,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...
17638,d56d3510-19b9-4129-b12d-63916321797c,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...
170,cfaeae33-1a2a-4349-91a2-67a6d0b4cb19,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder**,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...
17,33d3dfc4-de21-4972-b808-41080469ec6a,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders
29,5fec48f5-225f-4a20-a03a-333322a97619,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...
...,...,...,...,...,...,...,...,...,...,...
17370,edeaffcd-75b0-4140-9a85-5b5a59656504,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17466,eb863a41-5037-460c-ae2a-57410f977a2b,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17483,28e88104-952a-4b24-a049-052767b87e83,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17507,e9299962-4d2a-4085-8c5f-454fe593d446,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...
17529,3d230958-81d5-45e6-844e-b50baafa801f,d8586892-81d2-41de-a3b8-8ebc277b60f3,paragraph,NaN,902,1166,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders

In [73]:
last_paragraphs_df['next_page'] = None
last_paragraphs_df['next_page_type'] = None
next_pages = []
next_pages_type = []

for i, row in last_paragraphs_df.iterrows():
    _page = row['page']
    book_name = row['book_name']
    wanted_page = _page + 1
    next_page = first_paragraphs_df[(first_paragraphs_df['book_name']==book_name) & (first_paragraphs_df['page']==wanted_page)][['content', "node_type_in_tree"]]
    if(not next_page['content'].values):
        next_pages.append(None)
        next_pages_type.append(None)
    else:
        next_pages.append(next_page['content'].values[0])
        next_pages_type.append(next_page['node_type_in_tree'].values[0])

next_pages, next_pages_type

(['Communication and Learning Disorders',
  '**Pica.** The patient eats material that is not food ( p. 293 ).',
  'Individuals with intellectual developmental disorder (IDD), at one time called mental retardation, have two sorts of problem, one resulting from the other. First, there’s a fundamental deficit in their ability to think. This will be some combination of difficulties with abstract thinking, judgment, planning, problem solving, reasoning, and general learning (whether from academic study or from experience). Overall intelligence level, as determined by a standard individual test (not one of the group tests, which tend to be less accurate), will be markedly below average. In practical terms, this generally means an IQ of less than 70. (For infants, we can only subjectively judge intellectual functioning.)',
  'IDD may have biological or social causes, or both. Some of these etiologies (with the approximate percentages of all patients with IDD they represent) are given below. Note that the percentages are only approximate and the categories tend to flow into one another.',
  'skills. These patients experience difficulty in at least one of these domains across multiple life areas— family, school, work, and social relations.',
  '',
  'the interviewer. (However, much of the background information is obtained later from old school records and from his aunt, when she returns from vacation.)',
  'Adding in his homelessness (and a GAF score of 45), Grover’s diagnosis would be as follows:',
  'show unusual speech patterns and idiosyncratic use of phrases. They may speak too loudly or lack the prosody (lilt) that supplies the music that underlies speech. They may also fail to use body language or other nonverbal behavior to communicate—for example, the smiles or head nods with which most of us express approval. They may not understand the basis of humor (the concept that the words people use can have multiple or abstract meanings, for instance). Children with ASD often have trouble beginning or sustaining conversation; rather, they may talk to themselves or hold monologues on subjects that interest them, but not other people. They tend to ask questions over and again, even after they’ve obtained repeated answers.',
  '“splinter” skills—special abilities in computation, music, or rote memory that occasionally rise to the level of savantism. Physical conditions associated with ASD include phenylketonuria, fragile X syndrome, tuberous sclerosis, and a history of perinatal distress. Mental health comorbidity issues include anxiety disorders (especially prevalent) and depression (2– 30%), obsessive–compulsive behavior (in about one-third), attention- deficit/hyperactivity disorder (over half), intellectual developmental disorder (about half), and seizures (25–50%). Some patients complain of initial insomnia or a reduced need for sleep; a few even sleep days and remain awake nights. Researchers have recently reported an association of a form of autism with a gene responsible for kidney, breast, colon, brain, and skin cancer. The bottom line: Many patients with ASD will require additional diagnoses to capture the full complexity of their symptoms. ASD’s overall prevalence in the United States is currently stated as a bit above 1% of children; studies from other countries tend to report somewhat lower figures. Numbers have increased in recent years, at least in part due to increased awareness of ASD. ASD affects all cultural and socioeconomic groups, with boys affected two to three times as often as girls. Siblings of patients with ASD have an elevated risk for the same disorder.',
  'Note that there are varying degrees of ASD, some of which received separate diagnoses and codes in DSM-IV that no longer apply in DSM-5-TR. What was formerly called *Asperger’s disorder* is relatively milder; many communicate verbally quite well, yet still lack other skills needed to form social bonds with others.',
  'rocking and spinning helped calm her when she felt overstimulated. Much later, she remembers that being touched by other people caused such sensory overload that she would struggle to escape; hugging was “too overwhelming.” She couldn’t even tolerate the feel of edges of clothing, such as seams of her underwear. Temple was alert and well-coordinated, and she had normal hearing; yet she didn’t speak until after her fourth birthday. Later, she recalls her frustration at understanding what was said but being unable to respond. For many years thereafter, her voice was toneless and uninflected, without lilt or rhythm. Even as a college student, she would speak too loudly, unaware of the effect her voice was having on others. As a small child, Temple was taken to a psychiatrist who diagnosed her as having “childhood schizophrenia”; her parents were advised that she might need institutionalization. Instead, she received the benefit of private schooling, where her teachers taught the other students to accept her—and her eccentricities. For example, she was unable to meet the gaze of others and she lacked the sense of emotion normally attached to personal relationships. She might even hold a cat too tightly, not recognizing the signals of distress it was giving her. Uninterested in playing with other children, she would instead sit and spin objects such as coins or the lids of cans or bottles. She had an intense interest in odors and was fascinated by bright colors and the movement of sliding doors and other objects. Consistency was balm for Temple. At school age, she resisted change in her routines and would repeatedly ask the same questions. She reacted badly to Christmas and Thanksgiving because they entailed so much noise and confusion. As an older child, she became fixated on issues such as elections—the campaign buttons, bumper stickers, and posters for the governor of her state held special interest for her. But emotional nuance escaped her. With no internal compass for navigating personal relationships, understanding ordinary social communication was, for her, like being “an anthropologist on Mars.” Because she doesn’t have the feelings people usually attach to others, her social interactions had to be guided by intellect, not emotion. To communicate, she used lines scripted in advance—she didn’t have the instinct to speak in a socially appropriate manner. What she has learned of empathy she attained by visualizing herself in the other person’s place. Although Temple always rejected human contact, she nonetheless craved comfort. She found it one summer she spent on a farm, when she observed that a device used to immobilize cattle so that they could be immunized appeared to calm them. As a result, she designed and built a squeezing machine that applied mechanical pressure to her own body; the result was tranquility she hadn’t found by other means. Refined over the years, her invention led to her eventual career in creating devices used in animal husbandry. As an adult, Temple still has trouble responding to unexpected social situations, and she would have severe panic attacks were they not controlled with a small dose of the antidepressant imipramine. But she became salutatorian of her college graduating class; eventually she earned a PhD and ran her own company. She is world-famous as a designer of machinery that helps calm animals on their road to slaughter. And she is a sought-after speaker on autism. But if someone’s pager or cell',
  'phone goes off when she’s giving a lecture, it still causes her to lose her train of thought.',
  'F41.0 Panic disorder',
  'These behaviors typically decrease with adolescence, when many patients with ADHD settle down and become normally active and capable students. But some use substances or develop other forms of delinquent behavior. Adults may have interpersonal problems, alcohol or drug use, or personality disorders. Adults may also complain of trouble with concentration, disorganization, impulsivity, mood lability, overactivity, quick temper, and intolerance of stress.',
  'Coding Notes',
  'Denis’s son is 8, and until a month ago he was the terror of the second grade. But after 4 weeks on Ritalin, he has become less driven, his grades have improved, and he has become “almost a pleasure to live with.”\n\nFor years, Denis has suspected that he himself might have been hyperactive as a child. Like Randy, during the first few grades of elementary school he had been unable to sit still in his seat—bouncing up to use the pencil sharpener or to watch a passing ambulance. His teacher had once written a note home complaining that he talked constantly and that he “squirmed like a bug on a griddle.” It was part of the family mythology that he “crawled at 8 months, ran at 10.” On questioning, Denis admits that as a kid he was always on the go and could hardly tolerate waiting his turn for anything (“I felt like I was going to climb right out of my skin”).\n\nHe was almost stupifyingly forgetful. “Still am. I really can’t recall much else about my attention span when I was a kid—it’s too long ago,” he says. “But I have the general impression that I didn’t listen very well, just like I am today. Except when I took those two tablets by mistake.”\n\nThe remainder of Denis’s evaluation is unremarkable. He is in excellent physical health, and he has had no other mental health problems. Apart from some fidgeting in his chair, his appearance, speech, and affect are all completely ordinary, and he earns a perfect score on the MMSE.\n\nDenis was born in Ceylon, where his parents were both stationed as career diplomats with the Foreign Service. His father drank himself into an early grave, but not before divorcing his mother when their only child was 7 or 8. Because he was its subject, Denis vividly remembered their last major argument. His mother pleaded to have Denis’s behavioral problems evaluated, but his father banged his fist and swore that no kid of his was “going to see some damn shrink.” Not long afterward, his parents split up for good.\n\nDenis feels he has learned a lot from his father’s example—he doesn’t drink, has never tried drugs, and doesn’t argue with his wife; he had readily agreed when she suggested having Randy evaluated. “You always dream that your kids will have what you never did,” he says. “In our case, it’s Ritalin.”',
  'But even 3 decades later, he remembers enough hyperactivity/impulsivity symptoms to justify the childhood diagnosis. As adults, many such patients recognize restlessness as their predominant symptom. It would be a good idea for the clinician to verify what Denis thought he remembered, perhaps by obtaining old school records. In children, several other conditions make up the differential diagnosis. (Note that in a clinician’s office, many children with ADHD can sit still and focus attention well; the diagnosis often hinges on the history.) Those with intellectual developmental disorder learn slowly and may be overly active and impulsive, but patients with ADHD, once their attention is captured, are able to learn normally. Unlike children with autism spectrum disorder, patients with ADHD communicate without undue difficulty. Depressed patients may be agitated or have a poor attention span, but the duration is not usually lifelong. Many patients with Tourette’s disorder are also hyperactive, but those who only have ADHD will not show motor and vocal tics. Children reared in a chaotic social environment may also have difficulty with hyperactivity and inattention; although ADHD can be diagnosed in a child who lives in an unstable social environment, the process requires extra care and thought. Oppositional defiant disorder and conduct disorder may involve behavior that runs afoul of adults or peers, but those behaviors appear purposeful and are not accompanied by the feelings of remorse typical of ADHD behavior. However, many children with ADHD have comorbid conduct, oppositional defiant, or Tourette’s disorder. The differential diagnosis in adults includes antisocial personality disorder and mood disorders (patients with mood disorders can have problems with concentration and agitation). The diagnosis should not be made if the symptoms are better explained by schizophrenia, an anxiety disorder, or a personality disorder. As a child, Denis might have fulfilled criteria for ADHD, combined type; with the information currently available, however, this would be a tough sell to any coder with a hard nose. Although as an adult he continued to have severe problems concentrating, he overcame them with drive and raw intelligence. Until he compared his usual concentration to the kind of work he could do with medication, he never realized just how disabled he had been. Although we have some specifics that would constitute a current DSM-5-TR diagnosis (he was distractible—A1b), even with more information we might not be able to dredge up enough detail to make a full adult diagnosis by contemporary standards. As a clinician, I feel more comfortable with the qualifier “in partial remission.” A fuller examination, perhaps with added information from his wife (or boss), might justify a different final diagnosis. Oh, and I’d give him a GAF score of 70.',
  '**F90.8 Other Specified Attention-Deficit/Hyperactivity Disorder**',
  'Because tics look pretty much the same regardless of diagnosis, I’ve presented an example only in the context of Tourette’s disorder.',
  'Persistent (chronic) motor** **or vocal tic disorder** **Provisional tic disorder**',
  'Not long after he turned 13, Gordon noticed that a certain tension creeps into the back of his throat. He cannot describe it—it doesn’t tickle, and it doesn’t have a taste. It isn’t something he can swallow down. Sometimes a cough will temporarily relieve it, but more often it requires some form of vocalization to ease it. A bark or yelp usually works just fine. But at its most intense, only an obscenity will do. “Shit-fuck! Shit-fuck!” he yells again. Then, “Cunt!” Gordon shakes his head again and hoots twice. Halfway through his third year in high school, the vocal tics got so bad that they placed Gordon on “permanent suspension” until he could learn to sit in a classroom without creating pandemonium. The third clinician his parents consulted prescribed haloperidol. This relieved his symptoms completely, except for the tendency to blink when he is under stress. He remained on this drug until a month ago, when he read an article about tardive dyskinesia and began to worry about side effects. But once he stopped taking haloperidol, the full spectrum of tics rapidly returned. He was recently evaluated by his general physician, who pronounced him healthy. He has never abused street drugs or alcohol. Gordon is a neatly dressed, pleasant-appearing young man who sits quietly during most of the interview. He really seems quite ordinary, aside from exaggerated blinking, which occurs several times a minute. He sometimes accompanies the blinks by opening his mouth and curling his lips around his teeth. But every few minutes there occurs a small explosion of hoots, grunts, yelps, or barks, along with a variety of tics that involve his face, head, and shoulders. Irregularly, but with some frequency, his outbursts include the expletives quoted above—uttered with more volume than conviction. Afterward, he placidly resumes the conversation. The remainder of Gordon’s mental status is unremarkable. When he isn’t having tics, his speech is clear, coherent, relevant, and spontaneous, and he scores a perfect 30 on the MMSE. He worries about his symptoms but denies feeling especially depressed or anxious. He has never had hallucinations, delusions, or suicidal ideas. He also denies having obsessions or compulsions, adding, “You mean like Uncle George. He does rituals.”',
  'F95.2 Tourette’s disorder',
  'Some children have trouble mastering classroom skills such as coloring, printing, cursive, and cutting with scissors. Although the symptoms often stand on their own, for over half of patients DCD exists as part of a broader problem that includes attention deficits or learning problems such as dyslexia. Autism spectrum disorder has also been linked. After years of study, the cause is still unknown. In the individual case, a variety of physical conditions must be ruled out: muscular dystrophy, congenital myasthenia, cerebral palsy, central nervous system tumors, epilepsy, Friedreich’s ataxia, and Ehlers–Danlos disease. Obviously, late onset of motor incoordination would weigh heavily against DCD. Motor skill deficits can persist through adolescence and into adult life, though little is known about the course of DCD in adults.',
  'Patients who abuse amphetamines may become fascinated with handling mechanical devices such as watches or radios or picking at their own skin. Some will sort or rearrange small objects such as jewelry or even pebbles— *punding* (from a word popularized by amphetamine abusers), which may be related to excessive dopamine stimulation.',
  'Communication Disorders',
  'F80.0 Speech Sound Disorder',
  'Sudden onset may correlate with greater severity. As many as 3% of young children stutter; the percentage is higher for children with brain injuries or intellectual developmental disorder. Boys outnumber girls at least 3:1. Although reports vary, the prevalence in adults is about 1 in 1,000, of whom 80% are male. Stuttering runs in families, and there is some evidence of heritability. There are genetic (and some symptomatic) links to Tourette’s disorder, which is a dopamine- related disorder; dopamine antagonists have been used to ameliorate the effects of stuttering.',
  'Patients with SCD, whether children or adults, have difficulty understanding and using the pragmatic aspects of social communication, to the point that their conversations can be socially inappropriate. Yet they do not have the restricted interests and repetitive behaviors that would qualify them for a diagnosis of autism spectrum disorder. SCD can occur by itself or with other diagnoses, such as other communication disorders, specific learning disorders, or intellectual developmental disorder.',
  'the child reaches second grade. Two main groups of affected children have been identified. Most affected children have problems with language skills, including spelling and reading; these stem from a basic difficulty in processing sounds and symbols of language (in other words, they have a phonological processing disability). A smaller number have difficulties solving problems—visuospatial, motor, and/or tactile perceptual problems that manifest as dyscalculia. In one form or another, SLD affects 5–15% of Americans over the course of their lifetimes; boys are two or three times more often affected than girls. Of course, a child’s behavioral and social consequences are proportional to the severity of the impairment and to the available educational remediation and social support. Overall, however, as many as 40% of children formally diagnosed with SLD leave school before completing high school, against a national average of about 6%. These disorders are likely to persist into adult life, where the prevalence is about half that for children. Of the types of SLD, problems with math are the most likely to have an influence on adult functioning. Children with SLD are also more likely to have behavioral or emotional problems, specifically ADHD (which worsens the mental health prognosis), autism spectrum disorder, developmental coordination disorder, and communication disorders, as well as anxiety and mood disorders.',
  'accuracy tends to improve with time, fluency continues to be a problem into maturity. Adults may read slowly, confuse or mispronounce proper names and unfamiliar words, avoid reading aloud (due to embarrassment), or spell imaginatively (and choose words that are easier to spell). They may find reading such a tiring chore that they avoid recreational reading.',

In [74]:
last_paragraphs_df['next_page'] = next_pages
last_paragraphs_df['next_page_type'] = next_pages_type

In [75]:
last_paragraphs_df[last_paragraphs_df['next_page'].isna()]

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path,next_page,next_page_type
7017,64fc163d-2483-48af-8c45-5e72bcec1772,75629b5a-9e19-438d-83f0-a8b319d30974,paragraph,NaN,This category applies to presentations in whic...,253,leaf,DSM5_TR,Schizophrenia Spectrum and Other Psychotic Dis...,Schizophrenia Spectrum and Other Psychotic Dis...,NaN,NaN
2487,0b664b58-73a0-4272-89b1-d888e0b85022,78ef2470-8559-47de-9e38-bfc27924946f,paragraph,NaN,**The D’s:** • Differential diagnosis ( **phys...,281,leaf,DSM5_ME,Chapter 9: Feeding and Eating Disorders,Chapter 9: Feeding and Eating Disorders -> F50...,NaN,NaN
7849,f720420a-116f-41f2-8304-504ca067b2d0,17785910-f9e7-4ad8-878a-a64c715e5857,paragraph,NaN,1 In distinguishing grief from a major depress...,348,leaf,DSM5_TR,Depressive Disorders,Depressive Disorders,NaN,NaN
8463,fd14c61e-5fa7-4881-81dd-4d7728b62d4b,33d9ffbc-2b3c-4911-9f14-815a3ab3cd18,paragraph,NaN,262,406,leaf,DSM5_TR,Anxiety Disorders,Anxiety Disorders,NaN,NaN
8875,88fb5623-d2ab-4726-ab89-b2108ec6dd76,6c429699-4c6c-4b03-ba80-048a2aeb468a,paragraph,NaN,This category applies to presentations in whic...,446,leaf,DSM5_TR,Obsessive-Compulsive and Related Disorders,Obsessive-Compulsive and Related Disorders -> ...,NaN,NaN
10694,e1e91cab-fd3c-47fd-88a8-e3c42dba08ba,5426784d-eefb-47a8-b7cb-f7dbbc3a5a53,paragraph,NaN,This category applies to presentations in whic...,575,leaf,DSM5_TR,Feeding and Eating Disorders,Feeding and Eating Disorders -> ### **Unspecif...,NaN,NaN
5647,5bccfd87-d6c8-404c-a679-058186f9caea,acd719f1-1270-48e0-9ce9-767a9b4431b8,paragraph,NaN,"F10.24 Alcohol-induced depressive disorder, wi...",599,leaf,DSM5_ME,Chapter 20: Patients and Diagnoses,Chapter 20: Patients and Diagnoses,NaN,NaN
11410,20d429e8-5fb1-487a-9f40-b68c58c9688e,ccd83498-51d9-41db-a802-e47f2feb8f1a,paragraph,NaN,This category applies to presentations in whic...,670,leaf,DSM5_TR,Sleep-Wake Disorders,Sleep-Wake Disorders -> Unspecified Sleep-Wake...,NaN,NaN
12094,8031339a-be19-4ef7-8455-54e7b7c6127a,5041ac13-1bac-4503-b9a4-6850170d1a5b,paragraph,NaN,dysfunction that cause clinically significant ...,711,leaf,DSM5_TR,Sexual Dysfunctions,Sexual Dysfunctions,NaN,NaN
12620,14b692db-33bf-4321-a4d3-c7b833563d91,9f432f7c-9817-444d-879c-152601611eaa,paragraph,NaN,This category applies to presentations in whic...,752,leaf,DSM5_TR,"Disruptive, Impulse-Control, and Conduct Disor...","Disruptive, Impulse-Control, and Conduct Disor...",NaN,NaN
14192,b8a57387-fdf8-4729-b453-562d6dec607d,00ac18c5-fff8-4f08-a621-37d662b80a4b,paragraph,NaN,666,902,leaf,DSM5_TR,Substance-Related and Addictive Disorders,Substance-Related and Addictive Disorders,NaN,NaN
14209,5cdc4656-90c1-4f20-a7a9-d44efd340b12,61e8cdb6-1c46-470d-ba11-d6d898005278,paragraph,NaN,*Planning:* Ability to find the exit to a maze...,905,leaf,DSM5_TR,Neurocognitive Disorders,Neurocognitive Disorders -> **TABLE 1** **Neur...,NaN,NaN
15633,d736adbd-f30f-44be-8aa6-acc7de778005,9991bfe8-c362-4d4a-a02c-520079ef4ba8,paragraph,NaN,This category applies to presentations in whic...,1034,leaf,DSM5_TR,Personality Disorders,Personality Disorders,NaN,NaN
15952,44881633-3871-43f6-be76-278aee5c8975,dab9f966-51e3-49f3-8830-f5a382c1ed85,paragraph,NaN,802,1063,leaf,DSM5_TR,Paraphilic Disorders,Paraphilic Disorders,NaN,NaN
15981,61e57521-2cdc-4fc2-812e-a58cb6600c19,caefcb0c-44fc-44bb-b516-4987835aee2c,paragraph,NaN,806,1067,leaf,DSM5_TR,Other Mental Disorders and Additional Codes,Other Mental Disorders and Additional Codes,NaN,NaN
16100,f9487112-81ef-4465-9489-c2dec6453650,f902f3fc-7f77-41da-a29f-bcb110cb555d,paragraph,NaN,820,1083,leaf,DSM5_TR,Medication-Induced Movement Disorders and Othe...,Medication-Induced Movement Disorders and Othe...,NaN,NaN
17529,3d230958-81d5-45e6-844e-b50baafa801f,d8586892-81d2-41de-a3b8-8ebc277b60f3,paragraph,NaN,902,1166,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disorders,NaN,NaN

In [76]:
last_paragraphs_df =last_paragraphs_df[last_paragraphs_df['next_page'].notna()]
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path,next_page,next_page_type
10,435d3fa2-44dc-4ae4-a8a8-7abd27aae0f7,0d5aa42c-32b4-4885-9f1d-44c3e6b6c7ac,list_item,NaN,Unspecified intellectual developmental disorde...,34,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Neu...,Communication and Learning Disorders,parent
17638,d56d3510-19b9-4129-b12d-63916321797c,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...,**Pica.** The patient eats material that is no...,leaf
170,cfaeae33-1a2a-4349-91a2-67a6d0b4cb19,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder**,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,Individuals with intellectual developmental di...,leaf
17,33d3dfc4-de21-4972-b808-41080469ec6a,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"IDD may have biological or social causes, or b...",leaf
29,5fec48f5-225f-4a20-a03a-333322a97619,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,skills. These patients experience difficulty i...,leaf
...,...,...,...,...,...,...,...,...,...,...,...,...
17407,a0fa23d3-41d2-4565-813e-3c62a8f98112,8a4a3133-ca3d-408e-884f-b641d57a75f0,paragraph,NaN,"Similarly, traits are distinguished from most ...",1161,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,not form part of the trait definition. Importa...,leaf
17370,edeaffcd-75b0-4140-9a85-5b5a59656504,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,"psychiatric diagnoses. Notably, knowing the le...",leaf
17466,eb863a41-5037-460c-ae2a-57410f977a2b,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,esteem controlled by exaggerated concern about...,leaf
17483,28e88104-952a-4b24-a049-052767b87e83,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,distortions and confusion around self-appraisa...,leaf
17507,e9299962-4d2a-4085-8c5f-454fe593d446,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,Suspiciousness Expectations of—and sensitivity...,leaf

In [77]:
last_paragraphs_df = last_paragraphs_df[last_paragraphs_df['next_page_type']=='leaf']
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path,next_page,next_page_type
17638,d56d3510-19b9-4129-b12d-63916321797c,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...,**Pica.** The patient eats material that is no...,leaf
170,cfaeae33-1a2a-4349-91a2-67a6d0b4cb19,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder**,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,Individuals with intellectual developmental di...,leaf
17,33d3dfc4-de21-4972-b808-41080469ec6a,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"IDD may have biological or social causes, or b...",leaf
29,5fec48f5-225f-4a20-a03a-333322a97619,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,skills. These patients experience difficulty i...,leaf
32,a59b2707-9575-47e9-b371-707c568b44f9,ef528351-1f7d-4bd5-9874-41926f01272d,paragraph,NaN,Grover Peary was born when his mother was only...,40,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"the interviewer. (However, much of the backgro...",leaf
...,...,...,...,...,...,...,...,...,...,...,...,...
17407,a0fa23d3-41d2-4565-813e-3c62a8f98112,8a4a3133-ca3d-408e-884f-b641d57a75f0,paragraph,NaN,"Similarly, traits are distinguished from most ...",1161,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,not form part of the trait definition. Importa...,leaf
17370,edeaffcd-75b0-4140-9a85-5b5a59656504,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,"psychiatric diagnoses. Notably, knowing the le...",leaf
17466,eb863a41-5037-460c-ae2a-57410f977a2b,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,esteem controlled by exaggerated concern about...,leaf
17483,28e88104-952a-4b24-a049-052767b87e83,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,distortions and confusion around self-appraisa...,leaf
17507,e9299962-4d2a-4085-8c5f-454fe593d446,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,Suspiciousness Expectations of—and sensitivity...,leaf

In [79]:
last_paragraphs_df['content'] = last_paragraphs_df['content'] +  " " + last_paragraphs_df['next_page']
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path,next_page,next_page_type
17638,d56d3510-19b9-4129-b12d-63916321797c,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...,**Pica.** The patient eats material that is no...,leaf
170,cfaeae33-1a2a-4349-91a2-67a6d0b4cb19,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder** Indivi...,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,Individuals with intellectual developmental di...,leaf
17,33d3dfc4-de21-4972-b808-41080469ec6a,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"IDD may have biological or social causes, or b...",leaf
29,5fec48f5-225f-4a20-a03a-333322a97619,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,skills. These patients experience difficulty i...,leaf
32,a59b2707-9575-47e9-b371-707c568b44f9,ef528351-1f7d-4bd5-9874-41926f01272d,paragraph,NaN,Grover Peary was born when his mother was only...,40,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"the interviewer. (However, much of the backgro...",leaf
...,...,...,...,...,...,...,...,...,...,...,...,...
17407,a0fa23d3-41d2-4565-813e-3c62a8f98112,8a4a3133-ca3d-408e-884f-b641d57a75f0,paragraph,NaN,"Similarly, traits are distinguished from most ...",1161,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,not form part of the trait definition. Importa...,leaf
17370,edeaffcd-75b0-4140-9a85-5b5a59656504,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,"psychiatric diagnoses. Notably, knowing the le...",leaf
17466,eb863a41-5037-460c-ae2a-57410f977a2b,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,esteem controlled by exaggerated concern about...,leaf
17483,28e88104-952a-4b24-a049-052767b87e83,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,distortions and confusion around self-appraisa...,leaf
17507,e9299962-4d2a-4085-8c5f-454fe593d446,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,Suspiciousness Expectations of—and sensitivity...,leaf

In [81]:
last_paragraphs_df['node_id'] = "with_next_page_" + last_paragraphs_df['node_id']
last_paragraphs_df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path,next_page,next_page_type
17638,with_next_page_d56d3510-19b9-4129-b12d-6391632...,891dcda3-9a75-424c-a4d2-7573bae50c93,paragraph,NaN,Conduct disorder. A child persistently violate...,35,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> Att...,**Pica.** The patient eats material that is no...,leaf
170,with_next_page_cfaeae33-1a2a-4349-91a2-67a6d0b...,90f7c55b-f328-4b0e-bbb0-92f29d9cda9b,paragraph,NaN,**Intellectual Developmental Disorder** Indivi...,36,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,Individuals with intellectual developmental di...,leaf
17,with_next_page_33d3dfc4-de21-4972-b808-4108046...,f8a3e26e-e6c9-4923-ada3-8df8759f23d4,paragraph,NaN,The many causes of IDD include genetic abnorma...,37,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"IDD may have biological or social causes, or b...",leaf
29,with_next_page_5fec48f5-225f-4a20-a03a-333322a...,232fa459-59d5-4364-889f-d55d58e89513,paragraph,NaN,"From their earliest years, people with IDD are...",38,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders -> ###...,skills. These patients experience difficulty i...,leaf
32,with_next_page_a59b2707-9575-47e9-b371-707c568...,ef528351-1f7d-4bd5-9874-41926f01272d,paragraph,NaN,Grover Peary was born when his mother was only...,40,leaf,DSM5_ME,Chapter 1: Neurodevelopmental Disorders,Chapter 1: Neurodevelopmental Disorders,"the interviewer. (However, much of the backgro...",leaf
...,...,...,...,...,...,...,...,...,...,...,...,...
17407,with_next_page_a0fa23d3-41d2-4565-813e-3c62a8f...,8a4a3133-ca3d-408e-884f-b641d57a75f0,paragraph,NaN,"Similarly, traits are distinguished from most ...",1161,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,not form part of the trait definition. Importa...,leaf
17370,with_next_page_edeaffcd-75b0-4140-9a85-5b5a596...,1a353e27-cddb-47e9-9813-9919addf6075,paragraph,NaN,Disorder and trait constructs each add value t...,1162,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,"psychiatric diagnoses. Notably, knowing the le...",leaf
17466,with_next_page_eb863a41-5037-460c-ae2a-57410f9...,23b0ec71-150a-4fe9-bbaa-61ebc5dea0d2,paragraph,Intimacy,Is capable of forming and\n\ndesires to form r...,1163,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,esteem controlled by exaggerated concern about...,leaf
17483,with_next_page_28e88104-952a-4b24-a049-052767b...,0530729a-f481-4857-8562-f2959df96a95,paragraph,NaN,Desire for affiliation is\n\nlimited because o...,1164,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,distortions and confusion around self-appraisa...,leaf
17507,with_next_page_e9299962-4d2a-4085-8c5f-454fe59...,baac457c-65c9-403b-a7e2-b25eab471e7e,list_item,Restricted affectivity,Restricted affectivity Little reaction to emot...,1165,leaf,DSM5_TR,Alternative DSM-5 Model for Personality Disorders,Alternative DSM-5 Model for Personality Disord...,Suspiciousness Expectations of—and sensitivity...,leaf

In [82]:
last_paragraphs_df.to_json("books/dsm-tree/last_concated_with_first_nodes.jsonl", lines=True, orient='records')