In [1]:
import dspy 
from config.settings import settings

In [2]:

settings.model_dump()

{'llm_model': 'openai/gemma-4-31B-it',
 'llm_api_base': 'https://openrouter.ai/api/v1',
 'llm_api_key': 'Oj_63y_gBe8qlO4IDb0cR0w+FsrsOEr7bOCkPqxNrZ<Pg+sreD',
 'llm_timeout': 30,
 'llm_retry_attempts': 5,
 'llm_max_concurrent': 50}

In [2]:
import pandas as pd

dsm_df = pd.read_json("books/dsm-tree/dsm5-final.jsonl", lines=True)
dsm_df

,page_number,content,book_name,tree,llm
0,26,### **An Uncertain Diagnosis**\n\n### When you...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1,2,### **Also from James Morrison**\n\n### Diagno...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2,3,# **DSM-5-TR** **®**\n\n# **Made Easy**\n\n# *...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
3,4,EPUB Edition ISBN: 9781462551361\n\nCopyright ...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
4,5,"### *For Mary, always my sine qua non*",DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
...,...,...,...,...,...
1994,1368,"of prolonged grief disorder, 324 of PTSD, 311 ...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1995,1343,"Kleptomania, 539 – 541 Korea, prevalence of\n\...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1996,1373,"Systemic racism, 17 – 18\n\nTachypnea, and neu...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1997,1320,"Cannabis, 129 , 147 , 159 , 471 , 503 . *See a...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1998,1371,Substance/medication-induced major or mild neu...,DSM5_TR,"{'type': 'root', 'content': '', 'children': [{...",openai/gemma-4-31B-it

In [18]:
dsm_df = dsm_df.drop_duplicates(['page_number', 'book_name'])
dsm_df

,page_number,content,book_name,tree,llm
0,26,### **An Uncertain Diagnosis**\n\n### When you...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
1,2,### **Also from James Morrison**\n\n### Diagno...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2,3,# **DSM-5-TR** **®**\n\n# **Made Easy**\n\n# *...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
3,4,EPUB Edition ISBN: 9781462551361\n\nCopyright ...,DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
4,5,"### *For Mary, always my sine qua non*",DSM5_ME,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
...,...,...,...,...,...
2213,1368,"of prolonged grief disorder, 324 of PTSD, 311 ...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2214,1343,"Kleptomania, 539 – 541 Korea, prevalence of\n\...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2215,1373,"Systemic racism, 17 – 18\n\nTachypnea, and neu...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2216,1320,"Cannabis, 129 , 147 , 159 , 471 , 503 . *See a...",DSM5_TR,"{'type': 'root', 'heading': None, 'content': '...",openai/gemma-4-31B-it
2217,1371,Substance/medication-induced major or mild neu...,DSM5_TR,"{'type': 'root', 'content': '', 'children': [{...",openai/gemma-4-31B-it

In [20]:
dsm_df.to_json('books/dsm-tree/dsm5-final.jsonl', orient="records", lines=True)

In [21]:
import pandas as pd
import uuid

# Example tree (your input)
page_tree = {
    'type': 'root',
    'heading': None,
    'content': '',
    'children': [
        {'type': 'paragraph', 'heading': None, 'content': 'OK, so these pointers aren’t exactly iron-clad. Remember, they’re straws, not steel.', 'children': []},
        {'type': 'heading', 'heading': 'Essential Features of Psychotic Disorder Due to Another', 'content': 'Essential Features of Psychotic Disorder Due to Another', 'children': [
            {'type': 'heading', 'heading': 'Medical Condition', 'content': 'Medical Condition', 'children': [
                {'type': 'paragraph', 'heading': None, 'content': 'Through physiological means, a medical condition appears to have caused an illness that features obvious hallucinations or delusions.', 'children': []},
                {'type': 'heading', 'heading': 'The Fine Print', 'content': 'The Fine Print', 'children': [
                    {'type': 'paragraph', 'heading': None, 'content': 'For pointers on deciding when a physical condition may have caused a mental disorder, see the sidebar above .', 'children': []}
                ]},
                {'type': 'paragraph', 'heading': None, 'content': 'The D’s: • Distress or disability (work/academic, social, or personal impairment) • Differential diagnosis ( delirium, another mental disorder, substance-induced psychotic disorder, schizophrenia and its cousins, delusional disorder)', 'children': []},
                {'type': 'heading', 'heading': 'Coding Notes', 'content': 'Coding Notes', 'children': [
                    {'type': 'paragraph', 'heading': None, 'content': 'In recording the diagnosis, use the name of the responsible medical condition, and list first the medical condition, with its code number.', 'children': []},
                    {'type': 'paragraph', 'heading': None, 'content': 'Code, based on the predominant symptoms:\n\nF06.2 With delusions F06.0 With hallucinations', 'children': []},
                    {'type': 'paragraph', 'heading': None, 'content': 'You may specify severity, though you don’t have to ( p. 74 ).', 'children': []}
                ]}
            ]}
        ]},
        {'type': 'case_study', 'heading': 'Rodrigo Chavez', 'content': 'Rodrigo Chavez', 'children': [
            {'type': 'paragraph', 'heading': None, 'content': 'Since retiring from teaching at age 65, Rodrigo Chavez spends most of his time sitting alone in his room. Sometimes he plays the acoustic guitar; once or twice he’s shot targets at the rifle range. True to his lifelong custom, he never drinks. Other than his immediate family, he has few social contacts. “My cigarettes are my best friends,” he says during the forensic examination.', 'children': []},
            {'type': 'paragraph', 'heading': None, 'content': 'When Rodrigo is nearly 70, an inoperable carcinoma of the lung is diagnosed. After a course of palliative radiotherapy, he declines further treatment and settles down in his apartment to die. Four months later, he notices right-sided headaches that will sometimes awaken him in the middle of the night. Because the doctors have told him he is terminally ill, he doesn’t seek further medical attention.', 'children': []},
            {'type': 'paragraph', 'heading': None, 'content': 'Then, he begins to associate the headaches with natural gas, which he can smell coming out of the ventilator duct in his bathroom. When he calls to report the problem to Mrs. Riordan, his landlady, she sends around the building’s handyman, who can find nothing wrong. But both the odors and his headaches have increased; Rodrigo recalls that, weeks earlier, Mrs. Riordan went out several times to watch while', 'children': []}
        ]}
    ]
}

#  Recursive function to assign unique IDs and mark leaf/parent
def assign_ids(node, book_name="DSM5", parent_id=None, page_number=1, nodes_list=None):
    if nodes_list is None:
        nodes_list = []

    node_id = str(uuid.uuid4())  # unique ID
    # Determine if node is a leaf or has children
    node_type_in_tree = 'leaf' if not node.get('children') else 'parent'

    node_record = {
        'node_id': node_id,
        'parent_id': parent_id,
        'type': node.get('type'),
        'heading': node.get('heading'),
        'content': node.get('content'),
        'page': page_number,
        'node_type_in_tree': node_type_in_tree,
        'book_name': book_name
    }
    nodes_list.append(node_record)

    # Recursively assign IDs to children
    for child in node.get('children', []):
        assign_ids(child, book_name=book_name, parent_id=node_id, page_number=page_number, nodes_list=nodes_list)

    return nodes_list

# Assign IDs and get list of nodes
nodes_with_ids = assign_ids(page_tree, page_number=1)

# Convert to DataFrame
df = pd.DataFrame(nodes_with_ids)

# Display the DataFrame
df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name
0,67249cd7-8eb5-440d-820c-2b99af6af130,NaN,root,NaN,,1,parent,DSM5
1,06c09907-3fda-4119-aa86-f9ebf767e8ba,67249cd7-8eb5-440d-820c-2b99af6af130,paragraph,NaN,"OK, so these pointers aren’t exactly iron-clad...",1,leaf,DSM5
2,2fb59dd8-3ab9-4c68-b2b8-65db7442888e,67249cd7-8eb5-440d-820c-2b99af6af130,heading,Essential Features of Psychotic Disorder Due t...,Essential Features of Psychotic Disorder Due t...,1,parent,DSM5
3,f31b312f-c02c-4206-9507-d8a40902f1ea,2fb59dd8-3ab9-4c68-b2b8-65db7442888e,heading,Medical Condition,Medical Condition,1,parent,DSM5
4,7a654889-9a9d-4336-95ee-468e1a71e9f1,f31b312f-c02c-4206-9507-d8a40902f1ea,paragraph,NaN,"Through physiological means, a medical conditi...",1,leaf,DSM5
5,41fc8847-d77b-419b-aa54-7fa2f22d0ed3,f31b312f-c02c-4206-9507-d8a40902f1ea,heading,The Fine Print,The Fine Print,1,parent,DSM5
6,a00b4674-fb95-4baa-a24c-40a93ec2c9e5,41fc8847-d77b-419b-aa54-7fa2f22d0ed3,paragraph,NaN,For pointers on deciding when a physical condi...,1,leaf,DSM5
7,459cd8e6-3735-4834-8dc2-ce5fadc45c08,f31b312f-c02c-4206-9507-d8a40902f1ea,paragraph,NaN,The D’s: • Distress or disability (work/academ...,1,leaf,DSM5
8,a55a5356-d318-4220-9fcf-08c46f0fa4bd,f31b312f-c02c-4206-9507-d8a40902f1ea,heading,Coding Notes,Coding Notes,1,parent,DSM5
9,ebd74dd4-96b6-4de0-807d-ed28a708e850,a55a5356-d318-4220-9fcf-08c46f0fa4bd,paragraph,NaN,"In recording the diagnosis, use the name of th...",1,leaf,DSM5
10,987283e6-5034-49a0-b67c-04b5528b4c54,a55a5356-d318-4220-9fcf-08c46f0fa4bd,paragraph,NaN,"Code, based on the predominant symptoms:\n\nF0...",1,leaf,DSM5
11,81da50fb-326f-4124-987c-292f027ef239,a55a5356-d318-4220-9fcf-08c46f0fa4bd,paragraph,NaN,"You may specify severity, though you don’t hav...",1,leaf,DSM5
12,c1aeac2d-194c-4581-91f4-371c3674e2ca,67249cd7-8eb5-440d-820c-2b99af6af130,case_study,Rodrigo Chavez,Rodrigo Chavez,1,parent,DSM5
13,34ca1632-24b9-4fa0-8fcd-e940876b973a,c1aeac2d-194c-4581-91f4-371c3674e2ca,paragraph,NaN,"Since retiring from teaching at age 65, Rodrig...",1,leaf,DSM5
14,807a299c-af67-4f0f-b2d7-57cb7b89ebb7,c1aeac2d-194c-4581-91f4-371c3674e2ca,paragraph,NaN,"When Rodrigo is nearly 70, an inoperable carci...",1,leaf,DSM5
15,7e208982-8ab3-489d-b951-b1f632024d4b,c1aeac2d-194c-4581-91f4-371c3674e2ca,paragraph,NaN,"Then, he begins to associate the headaches wit...",1,leaf,DSM5

In [22]:
nodes_with_ids = []
for i, j in dsm_df.iterrows():
    nodes_with_ids = assign_ids(j['tree'], page_number=j['page_number'], nodes_list=nodes_with_ids,book_name=j['book_name'])
    df = pd.DataFrame(nodes_with_ids)
df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name
0,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,NaN,root,NaN,,26,parent,DSM5_ME
1,43099aac-71c3-4b15-bb63-ffab4f284ec8,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,An Uncertain Diagnosis,An Uncertain Diagnosis,26,parent,DSM5_ME
2,a8969d46-3b6b-4792-b551-e6262dacb375,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,When you’re not sure whether a diagnosis is co...,26,leaf,DSM5_ME
3,da108059-fd58-46ba-be3c-e1bacc129196,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,What about a patient who comes very close to m...,26,leaf,DSM5_ME
4,456b272a-fff1-4b82-9593-1432a6fb4f9b,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,Indicating Severity of a Disorder,Indicating Severity of a Disorder,26,leaf,DSM5_ME
...,...,...,...,...,...,...,...,...
25285,ed53efa4-3298-47b5-be50-d4a3ad437040,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"coding of, 822",1371,leaf,DSM5_TR
25286,3a6997fa-7b7f-405b-9da5-0844f1342dc6,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"contextual information in DSM-5-TR, 27",1371,leaf,DSM5_TR
25287,bb474643-6046-4f09-914e-03c066cb2032,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"depressive disorders and, 190 , 195 , 199 , 20...",1371,leaf,DSM5_TR
25288,a3d3f582-c223-4ee7-bd9b-733f83c818a8,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,depressive episodes with short-duration hypoma...,1371,leaf,DSM5_TR
25289,8260cb6c-43d0-4db0-82be-ba595088d09e,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"dissociative disorders and, 334 , 340",1371,leaf,DSM5_TR

In [3]:
# Define chapter start pages based on the TOC you provided
chapter_starts_ME = [
    (0, "Also Available"),
    (3, "Title Page"),
    (4, "Copyright"),
    (5, "Dedication"),
    (6, "About the Author"),
    (7, "Acknowledgments"),
    (9, "Contents"),
    (12, "Frequently Needed Tables"),
    (13, "Introduction"),
    (34, "Chapter 1: Neurodevelopmental Disorders"),
    (64, "Chapter 2: Schizophrenia Spectrum and Other Psychotic Disorders"),  # adjust as per actual TOC
    (117, "Chapter 3: Mood Disorders"),
    (164, "Chapter 4: Anxiety Disorders"),
    (190, "Chapter 5: Obsessive–Compulsive and Related Disorders"),
    (207, "Chapter 6: Trauma- and Stressor-Related Disorders"),
    (228, "Chapter 7: Dissociative Disorders"),
    (241, "Chapter 8: Somatic Symptom and Related Disorders"),
    (267, "Chapter 9: Feeding and Eating Disorders"),
    (283, "Chapter 10: Elimination Disorders"),
    (335, "Chapter 12: Sexual Dysfunctions"),
    (356, "Chapter 13: Gender Dysphoria"),
    (363, "Chapter 14: Disruptive, Impulse-Control, and Conduct Disorders"),
    (377, "Chapter 15: Substance-Related and Addictive Disorders"),
    (436, "Chapter 16: Cognitive Disorders"),
    (490, "Chapter 17: Personality Disorders"),
    (524, "Chapter 18: Paraphilic Disorders"),
    (548, "Chapter 19: Other Factors That May Need Clinical Attention"),
    (563, "Chapter 20: Patients and Diagnoses"),
    (600, "Appendix: Essential Tables"),
    (608, "Index"),
    (631, "About Guilford Press"),
    (632, "Discover Related Guilford Books"),
]

# Sort chapters by page (just in case)
chapter_starts_ME = sorted(chapter_starts_ME, key=lambda x: x[0])

# Function to map page to chapter
def get_chapter_for_page_for_dsm5_DE(page_number):
    chapter_name = None
    for i, (start_page, name) in enumerate(chapter_starts_ME):
        # If page is before the next chapter start or last chapter
        if i + 1 < len(chapter_starts_ME):
            next_start, _ = chapter_starts_ME[i + 1]
            if start_page <= page_number < next_start:
                chapter_name = name
                break
        else:  # Last chapter
            if page_number >= start_page:
                chapter_name = name
                break
    return chapter_name

# Example usage
pages_to_test = [10, 35, 120, 365, 500, 605]
for page in pages_to_test:
    print(f"Page {page} → {get_chapter_for_page_for_dsm5_DE(page)}")

Page 10 → Contents
Page 35 → Chapter 1: Neurodevelopmental Disorders
Page 120 → Chapter 3: Mood Disorders
Page 365 → Chapter 14: Disruptive, Impulse-Control, and Conduct Disorders
Page 500 → Chapter 17: Personality Disorders
Page 605 → Appendix: Essential Tables

In [4]:
# Updated chapter start pages based on your new TOC
chapter_starts = [
    (0, "Cover Page"),
    (6, "Title Page"),
    (7, "Copyright Page"),
    (8, "Contents"),
    (10, "DSM-5-TR Chairs and Review Groups"),
    (24, "DSM-5 Task Force and Work Groups"),
    (35, "Preface to DSM-5-TR"),
    (37, "Preface to DSM-5"),
    (41, "DSM-5-TR Classification"),
    (92, "Section I DSM-5 Basics"),
    (94, "Introduction"),
    (113, "Use of the Manual"),
    (123, "Cautionary Statement for Forensic Use of DSM-5"),
    (126, "Section II Diagnostic Criteria and Codes"),
    (130, "Neurodevelopmental Disorders"),  # you suggested 130 for unclear
    (207, "Schizophrenia Spectrum and Other Psychotic Disorders"),
    (254, "Bipolar and Related Disorders"),
    (301, "Depressive Disorders"),
    (349, "Anxiety Disorders"),
    (407, "Obsessive-Compulsive and Related Disorders"),
    (447, "Trauma- and Stressor-Related Disorders"),
    (490, "Dissociative Disorders"),
    (515, "Somatic Symptom and Related Disorders"),
    (543, "Feeding and Eating Disorders"),
    (576, "Elimination Disorders"),
    (586, "Sleep-Wake Disorders"),
    (671, "Sexual Dysfunctions"),
    (712, "Gender Dysphoria"),
    (726, "Disruptive, Impulse-Control, and Conduct Disorders"),
    (753, "Substance-Related and Addictive Disorders"),
    (903, "Neurocognitive Disorders"),
    (979, "Personality Disorders"),
    (1035, "Paraphilic Disorders"),
    (1064, "Other Mental Disorders and Additional Codes"),
    (1068, "Medication-Induced Movement Disorders and Other Adverse Effects"),
    (1100, "Other Conditions That May Be a Focus of Clinical Attention"),
    (1104, "Section III Emerging Measures and Models"),
    (1107, "Assessment Measures"),
    (1124, "Culture and Psychiatric Diagnosis"),
    (1145, "Alternative DSM-5 Model for Personality Disorders"),
    (1167, "Conditions for Further Study"),
    (1197, "Appendix"),
    (1307, "Index")
]

# Sort just in case
chapter_starts = sorted(chapter_starts, key=lambda x: x[0])

# Function to map page to chapter
def get_chapter_for_page_for_dsm5_TR(page_number):
    chapter_name = "Unclear Section"  # default if no match
    for i, (start_page, name) in enumerate(chapter_starts):
        if i + 1 < len(chapter_starts):
            next_start, _ = chapter_starts[i + 1]
            if start_page <= page_number < next_start:
                chapter_name = name
                break
        else:  # Last chapter
            if page_number >= start_page:
                chapter_name = name
                break
    return chapter_name

# Example usage
pages_to_test = [5, 40, 150, 365, 580, 720, 1000]
for page in pages_to_test:
    print(f"Page {page} → {get_chapter_for_page_for_dsm5_TR(page)}")

Page 5 → Cover Page
Page 40 → Preface to DSM-5
Page 150 → Neurodevelopmental Disorders
Page 365 → Anxiety Disorders
Page 580 → Elimination Disorders
Page 720 → Gender Dysphoria
Page 1000 → Personality Disorders

In [5]:
def get_chapter_for_page(book_name, page_number):
    if(book_name=="DSM5_TR"):
        return get_chapter_for_page_for_dsm5_TR(page_number)
    else:
        return get_chapter_for_page_for_dsm5_DE(page_number)

get_chapter_for_page("DSM_DE", 1)

'Also Available'

In [7]:
df['section'] = df.apply(lambda row: get_chapter_for_page(row['book_name'], row['page']), axis=1)
df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
0,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,NaN,root,NaN,,26,parent,DSM5_ME,Introduction,DSM-5 Task Force and Work Groups
1,43099aac-71c3-4b15-bb63-ffab4f284ec8,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,An Uncertain Diagnosis,An Uncertain Diagnosis,26,parent,DSM5_ME,Introduction,DSM-5 Task Force and Work Groups
2,a8969d46-3b6b-4792-b551-e6262dacb375,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,When you’re not sure whether a diagnosis is co...,26,leaf,DSM5_ME,Introduction,DSM-5 Task Force and Work Groups -> An Uncerta...
3,da108059-fd58-46ba-be3c-e1bacc129196,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,What about a patient who comes very close to m...,26,leaf,DSM5_ME,Introduction,DSM-5 Task Force and Work Groups -> An Uncerta...
4,456b272a-fff1-4b82-9593-1432a6fb4f9b,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,Indicating Severity of a Disorder,Indicating Severity of a Disorder,26,leaf,DSM5_ME,Introduction,DSM-5 Task Force and Work Groups
...,...,...,...,...,...,...,...,...,...,...
25285,ed53efa4-3298-47b5-be50-d4a3ad437040,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"coding of, 822",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25286,3a6997fa-7b7f-405b-9da5-0844f1342dc6,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"contextual information in DSM-5-TR, 27",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25287,bb474643-6046-4f09-914e-03c066cb2032,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"depressive disorders and, 190 , 195 , 199 , 20...",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25288,a3d3f582-c223-4ee7-bd9b-733f83c818a8,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,depressive episodes with short-duration hypoma...,1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25289,8260cb6c-43d0-4db0-82be-ba595088d09e,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"dissociative disorders and, 334 , 340",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...

In [10]:
df.to_json("books/dsm-tree/tree_with_IDs.json", orient="records", lines=True)

In [6]:
import pandas as pd

df = pd.read_json("books/dsm-tree/tree_with_IDs.json", lines=True)
df

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
0,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,NaN,root,NaN,,26,parent,DSM5_ME,DSM-5 Task Force and Work Groups,DSM-5 Task Force and Work Groups
1,43099aac-71c3-4b15-bb63-ffab4f284ec8,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,An Uncertain Diagnosis,An Uncertain Diagnosis,26,parent,DSM5_ME,DSM-5 Task Force and Work Groups,DSM-5 Task Force and Work Groups
2,a8969d46-3b6b-4792-b551-e6262dacb375,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,When you’re not sure whether a diagnosis is co...,26,leaf,DSM5_ME,DSM-5 Task Force and Work Groups,DSM-5 Task Force and Work Groups -> An Uncerta...
3,da108059-fd58-46ba-be3c-e1bacc129196,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,What about a patient who comes very close to m...,26,leaf,DSM5_ME,DSM-5 Task Force and Work Groups,DSM-5 Task Force and Work Groups -> An Uncerta...
4,456b272a-fff1-4b82-9593-1432a6fb4f9b,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,Indicating Severity of a Disorder,Indicating Severity of a Disorder,26,leaf,DSM5_ME,DSM-5 Task Force and Work Groups,DSM-5 Task Force and Work Groups
...,...,...,...,...,...,...,...,...,...,...
25285,ed53efa4-3298-47b5-be50-d4a3ad437040,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"coding of, 822",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25286,3a6997fa-7b7f-405b-9da5-0844f1342dc6,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"contextual information in DSM-5-TR, 27",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25287,bb474643-6046-4f09-914e-03c066cb2032,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"depressive disorders and, 190 , 195 , 199 , 20...",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25288,a3d3f582-c223-4ee7-bd9b-733f83c818a8,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,depressive episodes with short-duration hypoma...,1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25289,8260cb6c-43d0-4db0-82be-ba595088d09e,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"dissociative disorders and, 334 , 340",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...

In [30]:
_samp = df[(df['book_name']=="DSM5_ME") & (df['page']==100)]
_samp

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section
809,340b858d-c14c-4de5-ac1c-3c38b567f137,NaN,root,NaN,,100,parent,DSM5_ME,Introduction
810,ff491493-ea4d-4e01-8317-5c6bffd5e88f,340b858d-c14c-4de5-ac1c-3c38b567f137,heading,Essential Features of Schizoaffective Disorder,Essential Features of **Schizoaffective Disord...,100,parent,DSM5_ME,Introduction
811,495ab417-f329-4129-a624-a47eb70d6a96,ff491493-ea4d-4e01-8317-5c6bffd5e88f,paragraph,NaN,During a continuous period of illness the pers...,100,leaf,DSM5_ME,Introduction
812,d3573465-ecac-4eeb-9f17-502d1da4d4c3,340b858d-c14c-4de5-ac1c-3c38b567f137,heading,The Fine Print,**The Fine Print**,100,parent,DSM5_ME,Introduction
813,87f9b585-75d7-47f7-b2c0-3e4b34ca5aa0,d3573465-ecac-4eeb-9f17-502d1da4d4c3,paragraph,NaN,"Schizophrenia symptoms: For at least 1 month, ...",100,leaf,DSM5_ME,Introduction
814,0a36e8a9-9e89-4717-9094-df0a85f80037,d3573465-ecac-4eeb-9f17-502d1da4d4c3,paragraph,NaN,Manic episode: Markedly high or irritable mood...,100,leaf,DSM5_ME,Introduction
815,2a9b3deb-e1d5-45b8-8789-28e6fd25eea4,d3573465-ecac-4eeb-9f17-502d1da4d4c3,paragraph,NaN,Major depressive episode: Depressed mood most ...,100,leaf,DSM5_ME,Introduction
816,4603c15f-2770-4f4e-a348-1eabfab55feb,340b858d-c14c-4de5-ac1c-3c38b567f137,paragraph,NaN,**The D’s:** • Duration (a total of 1+ months)...,100,leaf,DSM5_ME,Introduction
817,46fd52ff-4444-46b6-9462-7c567304446c,340b858d-c14c-4de5-ac1c-3c38b567f137,heading,Coding Notes,**Coding Notes**,100,parent,DSM5_ME,Introduction
818,4f2fc7a3-dec2-451e-ac77-f4eff4e38c32,46fd52ff-4444-46b6-9462-7c567304446c,paragraph,NaN,Specify:\n\n**F25.0 Bipolar type** (if during ...,100,leaf,DSM5_ME,Introduction
819,1620ba11-bc01-4d64-b70d-9e84e009f62b,46fd52ff-4444-46b6-9462-7c567304446c,paragraph,NaN,Specify:\n\n**With catatonia** ( p. 100 ),100,leaf,DSM5_ME,Introduction
820,b6b74ac8-b363-48ec-a44e-46d9a9e958eb,46fd52ff-4444-46b6-9462-7c567304446c,paragraph,NaN,"If the disorder has lasted at least 1 year, sp...",100,leaf,DSM5_ME,Introduction
821,bd212291-a15d-41b9-a471-f0216eb28e76,46fd52ff-4444-46b6-9462-7c567304446c,paragraph,NaN,"You may specify severity, though you don’t hav...",100,leaf,DSM5_ME,Introduction
822,8849d36e-aba8-4f2b-a482-d1ca350a6585,340b858d-c14c-4de5-ac1c-3c38b567f137,case_study,Velma Dean,**Velma Dean**,100,leaf,DSM5_ME,Introduction

In [8]:

# Assuming df is your DataFrame
df['_path'] = None

# Quick lookups for content and parent_id
node_content_map = df.set_index('node_id')['content'].to_dict()
node_parent_map = df.set_index('node_id')['parent_id'].to_dict()
node_section_map = df.set_index('node_id')['section'].to_dict()

def build_path_exclude_current(node_id):
    path = []
    current_id = node_parent_map.get(node_id)  # start from the parent of current node

    # Traverse up until the root
    while pd.notna(current_id):
        content = node_content_map.get(current_id)
        if content and str(content).strip() != "":
            path.insert(0, content)  # prepend to keep hierarchical order
        current_id = node_parent_map.get(current_id)

    # Prepend Section at the start
    section = node_section_map.get(node_id)
    if section:
        path.insert(0, section)

    return ' -> '.join(path)

# Apply to all rows
df['_path'] = df['node_id'].apply(build_path_exclude_current)

# Preview
prew = df[['content', 'section', '_path','node_type_in_tree']]
prew

,content,section,_path,node_type_in_tree
0,,Introduction,Introduction,parent
1,An Uncertain Diagnosis,Introduction,Introduction,parent
2,When you’re not sure whether a diagnosis is co...,Introduction,Introduction -> An Uncertain Diagnosis,leaf
3,What about a patient who comes very close to m...,Introduction,Introduction -> An Uncertain Diagnosis,leaf
4,Indicating Severity of a Disorder,Introduction,Introduction,leaf
...,...,...,...,...
25285,"coding of, 822",Index,Index -> Suicidal thoughts or behavior. *See a...,leaf
25286,"contextual information in DSM-5-TR, 27",Index,Index -> Suicidal thoughts or behavior. *See a...,leaf
25287,"depressive disorders and, 190 , 195 , 199 , 20...",Index,Index -> Suicidal thoughts or behavior. *See a...,leaf
25288,depressive episodes with short-duration hypoma...,Index,Index -> Suicidal thoughts or behavior. *See a...,leaf
25289,"dissociative disorders and, 334 , 340",Index,Index -> Suicidal thoughts or behavior. *See a...,leaf

In [9]:
df[df['node_type_in_tree']=='leaf'].loc[1000]

node_id                           8a89bbc2-faac-4454-aaa2-6efea7667e92
parent_id                         f97fe520-7765-40ae-a412-d2b0918f9e79
type                                                         list_item
heading                                                            NaN
content              2. Patients may use substances (especially alc...
page                                                               130
node_type_in_tree                                                 leaf
book_name                                                      DSM5_ME
section                                      Chapter 3: Mood Disorders
_path                                        Chapter 3: Mood Disorders
Name: 1000, dtype: object

In [75]:
df[df['node_type_in_tree']=='leaf']

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
2,a8969d46-3b6b-4792-b551-e6262dacb375,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,When you’re not sure whether a diagnosis is co...,26,leaf,DSM5_ME,Introduction,Introduction -> An Uncertain Diagnosis
3,da108059-fd58-46ba-be3c-e1bacc129196,43099aac-71c3-4b15-bb63-ffab4f284ec8,paragraph,NaN,What about a patient who comes very close to m...,26,leaf,DSM5_ME,Introduction,Introduction -> An Uncertain Diagnosis
4,456b272a-fff1-4b82-9593-1432a6fb4f9b,f7f2bb1f-b8f0-4796-86fb-df24f5e970fc,heading,Indicating Severity of a Disorder,Indicating Severity of a Disorder,26,leaf,DSM5_ME,Introduction,Introduction
7,e5d89330-82ef-415a-bac6-12042ccac85f,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,Diagnosis Made Easier:\n\nPrinciples and Techn...,2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
8,b86a263d-7563-4a81-89a2-0296dd0e1273,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,"The First Interview, Fourth Edition",2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
...,...,...,...,...,...,...,...,...,...,...
25285,ed53efa4-3298-47b5-be50-d4a3ad437040,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"coding of, 822",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25286,3a6997fa-7b7f-405b-9da5-0844f1342dc6,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"contextual information in DSM-5-TR, 27",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25287,bb474643-6046-4f09-914e-03c066cb2032,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"depressive disorders and, 190 , 195 , 199 , 20...",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25288,a3d3f582-c223-4ee7-bd9b-733f83c818a8,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,depressive episodes with short-duration hypoma...,1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...
25289,8260cb6c-43d0-4db0-82be-ba595088d09e,8a8bce5a-8b85-4cb4-873b-c7b90dbbfdcd,list_item,NaN,"dissociative disorders and, 334 , 340",1371,leaf,DSM5_TR,Index,Index -> Suicidal thoughts or behavior. *See a...

In [76]:
df[df['book_name']=='DSM5_ME'].sort_values("page")

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
11,ede348ff-d64b-44a7-9099-1e2c4ea9ea2f,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,When Psychological Problems Mask Medical Disor...,2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
12,c022f234-1c81-425a-b7e8-0350b9eb3c3b,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,"For more information, see *www.guilford.com/mo...",2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
6,8e85080d-9705-4c73-8b2c-4729e836952a,350ffe58-9c7b-4783-867b-61ecbf5df98d,heading,Also from James Morrison,Also from James Morrison,2,parent,DSM5_ME,Also Available,Also Available
7,e5d89330-82ef-415a-bac6-12042ccac85f,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,Diagnosis Made Easier:\n\nPrinciples and Techn...,2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
9,77ba06cc-1ef7-4cbd-b4a6-12d05979cbfb,8e85080d-9705-4c73-8b2c-4729e836952a,paragraph,NaN,Interviewing Children and Adolescents:\n\nSkil...,2,leaf,DSM5_ME,Also Available,Also Available -> Also from James Morrison
...,...,...,...,...,...,...,...,...,...,...
6306,a9ca856e-2c7d-4397-a830-04ebbfc5752d,07203637-4bd4-4b62-ba74-3d0b2b56ddd7,heading,Guilford Journals Online,Guilford Journals Online,632,parent,DSM5_ME,Discover Related Guilford Books,Discover Related Guilford Books
6186,75a1ff6e-839f-4c29-8e80-1692fbcd2dee,a8e5b984-afb5-476d-bec1-fb549751540a,paragraph,NaN,The diagram shows a rectangular bar to denote ...,633,leaf,DSM5_ME,Discover Related Guilford Books,Discover Related Guilford Books
6187,a2d11484-ef1a-4d4c-9f35-f0c0a92c9f67,a8e5b984-afb5-476d-bec1-fb549751540a,paragraph,NaN,Psychosis symptoms are denoted by backward sla...,633,leaf,DSM5_ME,Discover Related Guilford Books,Discover Related Guilford Books
6185,9caa8f80-c8cb-4404-8f4a-6709c44f1907,a8e5b984-afb5-476d-bec1-fb549751540a,paragraph,NaN,Extended image description for Page 89,633,leaf,DSM5_ME,Discover Related Guilford Books,Discover Related Guilford Books
6184,a8e5b984-afb5-476d-bec1-fb549751540a,NaN,root,NaN,,633,parent,DSM5_ME,Discover Related Guilford Books,Discover Related Guilford Books

In [77]:
_samp[_samp['node_type_in_tree']=='parent']['content'].tolist(), _samp[_samp['node_type_in_tree']=='parent']['heading'].tolist()

(['',
  'Essential Features of **Schizoaffective Disorder**',
  '**The Fine Print**',
  '**Coding Notes**'],
 [nan,
  'Essential Features of Schizoaffective Disorder',
  'The Fine Print',
  'Coding Notes'])

In [80]:
df[df["page"]==134]

,node_id,parent_id,type,heading,content,page,node_type_in_tree,book_name,section,_path
1019,01aa56a7-7d50-4314-90f3-11e21ecc92d3,NaN,root,NaN,,134,parent,DSM5_ME,Chapter 3: Mood Disorders,Chapter 3: Mood Disorders
1020,1fb434f3-304e-412d-b0e4-b3ca202409ae,01aa56a7-7d50-4314-90f3-11e21ecc92d3,paragraph,NaN,"out for any postpartum patient, but she seems ...",134,leaf,DSM5_ME,Chapter 3: Mood Disorders,Chapter 3: Mood Disorders
1021,60bc383e-67bb-420d-b539-ee6be3f1428b,01aa56a7-7d50-4314-90f3-11e21ecc92d3,case_study,Winona Fisk,"By the time she turned 21, Winona Fisk had alr...",134,leaf,DSM5_ME,Chapter 3: Mood Disorders,Chapter 3: Mood Disorders
1022,3111bfa4-6685-4237-93d7-30eb90103c68,01aa56a7-7d50-4314-90f3-11e21ecc92d3,heading,Evaluation of Winona Fisk,Evaluation of Winona Fisk,134,parent,DSM5_ME,Chapter 3: Mood Disorders,Chapter 3: Mood Disorders
1023,68f4ca53-0a0e-43a3-8ee6-8a18d56025f3,3111bfa4-6685-4237-93d7-30eb90103c68,paragraph,NaN,Winona’s two previous episodes of bipolar I di...,134,leaf,DSM5_ME,Chapter 3: Mood Disorders,Chapter 3: Mood Disorders -> Evaluation of Win...
8732,9193d205-5df5-4958-b79c-6289f9db4156,NaN,root,NaN,,134,parent,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders
8733,3fcdcb9c-31ff-474c-9e57-941b26c77263,9193d205-5df5-4958-b79c-6289f9db4156,heading,**Diagnostic Criteria**,**Diagnostic Criteria**,134,parent,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders
8734,f2517e10-748a-49d0-a760-4a28e6e5ae59,3fcdcb9c-31ff-474c-9e57-941b26c77263,paragraph,NaN,Intellectual developmental disorder (intellect...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8735,18f0d3ce-3071-4da6-af9c-c6a6fdc43005,3fcdcb9c-31ff-474c-9e57-941b26c77263,criteria_block,NaN,,134,parent,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8736,79cc4706-14e0-4a83-ad63-00beba9e7740,18f0d3ce-3071-4da6-af9c-c6a6fdc43005,list_item,NaN,"A. Deficits in intellectual functions, such as...",134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8737,94ac80a0-84b0-4cdd-b07a-cbb1942495e7,18f0d3ce-3071-4da6-af9c-c6a6fdc43005,list_item,NaN,B. Deficits in adaptive functioning that resul...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8738,f1354844-c979-4e1b-bfc3-a65369dfb131,18f0d3ce-3071-4da6-af9c-c6a6fdc43005,list_item,NaN,C. Onset of intellectual and adaptive deficits...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8739,d2854692-11fd-4345-a2d6-4998373805f6,3fcdcb9c-31ff-474c-9e57-941b26c77263,paragraph,NaN,38,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8740,a0214ffd-d550-4103-bd73-d417aac81270,3fcdcb9c-31ff-474c-9e57-941b26c77263,paragraph,NaN,**Note:** The term *intellectual developmental...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8741,2bbff51f-277b-4f77-acf0-d5fa73c54fc6,3fcdcb9c-31ff-474c-9e57-941b26c77263,paragraph,NaN,**F70 Mild** **F71 Moderate** **F72 Severe** *...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8742,d1aee87b-27ae-406a-8bcb-5a9e338aecea,3fcdcb9c-31ff-474c-9e57-941b26c77263,paragraph,NaN,39,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8743,44f7f54b-172f-462a-9cb3-a49ac49c20fb,3fcdcb9c-31ff-474c-9e57-941b26c77263,heading,**TABLE 1** **Severity levels for intellectual...,**TABLE 1** **Severity levels for intellectual...,134,parent,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...
8744,304b9340-6ccc-4c1d-abf8-a0407c2b3be9,44f7f54b-172f-462a-9cb3-a49ac49c20fb,paragraph,NaN,**Severity**\n\n**level** **Conceptual domain*...,134,leaf,DSM5_TR,Neurodevelopmental Disorders,Neurodevelopmental Disorders -> **Diagnostic C...

In [ ]:
df.groupby("")

In [ ]:


lm = dspy.LM(
    model=settings.llm_model,
    api_base=settings.llm_api_base,
    api_key=settings.llm_api_key,
    timeout=settings.llm_timeout,
)
dspy.settings.configure(lm=lm, temperature=0.0)

In [3]:
from signatures.entity_extraction import DisorderEntityExtractor
from signatures.entity_example import case_study_para2_entities, case_study_para1_entities, example_entities
from dspy.teleprompt import BootstrapFewShot

trainset = [case_study_para2_entities, case_study_para1_entities, example_entities]
cot = dspy.ChainOfThought(DisorderEntityExtractor)
optimizer = BootstrapFewShot()
compiled_cot = optimizer.compile(
    cot,
    trainset=trainset
)

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00,  7.73it/s]

Bootstrapped 3 full traces after 2 examples for up to 1 rounds, amounting to 3 attempts.